apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-edge
  labels:
    app: hello-edge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-edge
  template:
    metadata:
      labels:
        app: hello-edge
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo
          args:
            - "-text=hello from k3s gitops"
          ports:
            - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: hello-edge-svc
  labels:
    app: hello-edge
spec:
  selector:
    app: hello-edge
  ports:
    - port: 80
      targetPort: 5678

